### ISSUE TITLE
로그인 관련 버그 해결

### ISSUE THREAD

**Issue by cherryiJuice** [FashionForecast/FashionForecast-server#120]
### 🐞 버그 설명

- 회원이 중복되어 저장되는 문제 발생 
- 닉네임이 중복이면 저장되지 않은 문제
- 헤더에 토큰을 저장해도 인식하지 못하는 문제

### ✅ 예상 결과

1. 더이상 멤버가 중복되어 저장되지 않음
2. 닉네임이 유니크 하지 않아도 저장됨
3. 헤더에 저장된 토큰을 인식하여 인증 성공 여부 응답

### ❗ 실제 결과

1. 더이상 멤버가 중복되어 저장되지 않음
2. 닉네임이 유니크 하지 않아도 저장됨
3. 헤더에 저장된 토큰을 인식하여 인증 성공 여부 응답

### 💻 버그 시뮬레이션

1. 멤버가 중복되어서 저장되었던 이유는 `getMember()` 메서드에서 `orElse`를 사용하기 때문이였습니다. `orElse`는 `Optional`이 비어 있든 말든 항상 `orElse`에 있는 메서드를 호출합니다. 그래서 `findByJoinTypeAndSocialId`가 비어 있지 않아도 `savedMember` 메서드가 실행되고, 이미 존재하는 회원이 중복으로 저장될 수 있습니다. 따라서 `orElseGet`을 사용하여 `Optional`이 비어 있을 때만 `savedMember` 메서드를 호출하도록 했습니다.
2. 회원이 중복되는 문제때문에 발견하게 되었는데 같은 닉네임은 저장되지 않는 문제가 발생했습니다. 따라서 dev와 local DB를 확인해보니 닉네임이 unique key로 되어 있는 것을 발견했습니다. 따라서 이를 제거했습니다. (배포 DB는 정상적으로 되어있었습니다.)
3. 헤더에 토큰을 저장하기로 했었는데 제가 실수로 까먹고 쿠키에 저장한다고 생각하여 쿠키에 있는 액세스 토큰을 가져오고 있었습니다. 따라서 이를 헤더에서 가져오는 것으로 수정하였습니다.
4. `jwtService`에 `getAuthentication` 반환값이랑 컨트롤러의 `@AuthenticationPrincipal` 반환값이랑 달라서 principle을 인식하지 못하는 문제가 발생했습니다. 새로운 인증객체를 만들어서 통일했습니다.

**Comment by phk1128** [comment]
굿굿 👍👍
